# Menu
menu:
  首页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# Miscellaneous
favicon: /favicon.ico
brand: /images/zha.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/zha.png

# Content
excerpt_link: ✔

# MIIT ICP/IP/DOMAIN
beian:
  enable: false
  number: 
  url: https://beian.miit.gov.cn/


# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true


# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'

#fireworksjs: true
lihwjs: true
live2d:
  enable: true

gitalk:
  enable: true
  clientID: de6620f1d7af58fe6167  
  clientSecret: 0620d04cfe36481d4a41a6d8d3eacc47270b76d2 
  repo: Gitalk  
  owner: poorzha 
  admin: poorzha  

#博客自动阅读全文
auto_excerpt:
  enable: true
  length: 100

# 百度统计
baidustatistic:
  enable: true
  siteid: 28c661f0c6292a2c1e721f1b08b229fd